In [1]:
import pandas
dataframe = pandas.read_csv("dataset.csv")
dataframe['date'] = pandas.to_datetime(dataframe['date'], format='%Y-%m-%d %H:%M:%S')

In [2]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  datetime64[ns]
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(2)
memory usage: 4.4 MB

In [3]:
dataframe.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
dataframe.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [5]:
print(list(dict.fromkeys(dataframe.columns)))

['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1', 'rv2']

In [6]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/feature_vs_date"
# DPI = 100
# for i in range(1 , 2):
# # for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         graph.title(column_list[i] + " vs " + column_list[0])
#         graph.xlabel(column_list[0])
#         graph.ylabel(column_list[i])
#         graph.plot(dataframe[column_list[0]], dataframe[column_list[i]], linewidth=1)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + ".png", dpi = DPI)
#         graph.show()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + ".png", dpi = DPI)
#         graph.show()

In [7]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/feature_vs_week1"
# filtered_week1_dataset = dataframe.loc[ ("2016-01-11" < dataframe["date"]) & (dataframe["date"] <= "2016-01-18")]
# DPI = 100
# # for i in range(1 , 2):
# for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         graph.title(column_list[i] + " vs " + column_list[0] + "(week 1)")
#         graph.xlabel(column_list[0])
#         graph.ylabel(column_list[i])
#         graph.plot(filtered_week1_dataset[column_list[0]], filtered_week1_dataset[column_list[i]], linewidth=1)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + "_week1.png", dpi = DPI)
#         graph.show()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + "_week1.png", dpi = DPI)
#         graph.show()

In [8]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/frequency"
# DPI = 100
# for i in range(1 , 2):
# # for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         feature_frequency_dataframe = dataframe[column_list[i]].value_counts()
#         feature_frequency_dataframe.hist()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)

In [10]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
time_dataframe = dataframe
x = dataframe[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint']]
y = dataframe['Appliances']
linear_regression = LinearRegression()
linear_regression.fit(x, y)
print('Intercept: \n', linear_regression.intercept_)
print('Coefficients: \n', linear_regression.coef_)

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 
print_model = model.summary()
print(print_model)

Intercept:
 34.66165576249416
Coefficients:
 [ 3.87404950e-01  1.60676718e+01 -2.03023792e+01 -1.44106352e+01
  2.53782507e+01  5.04805794e+00  2.97566214e+00  1.94699006e+00
 -1.10836980e-02  2.39073626e-01  7.66167382e+00  3.47156267e-01
  1.13054583e+00 -1.84314955e+00  1.01537621e+01 -5.90648932e+00
 -2.21080671e+01 -1.50004806e+00 -1.06453244e+01  1.23031901e-01
 -9.12029514e-01  2.12928730e+00  1.76197324e-01  5.08145345e+00]
                            OLS Regression Results
==============================================================================
Dep. Variable:             Appliances   R-squared:                       0.146
Model:                            OLS   Adj. R-squared:                  0.145
Method:                 Least Squares   F-statistic:                     140.9
Date:                Mon, 20 Mar 2023   Prob (F-statistic):               0.00
Time:                        15:56:28   Log-Likelihood:            -1.1782e+05
No. Observations:               19735   AIC:                         2.357e+05
Df Residuals:                   19710   BIC:                         2.359e+05
Df Model:                          24
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          34.6617     95.624      0.362      0.717    -152.769     222.093
T1              0.3874      1.863      0.208      0.835      -3.263       4.038
RH_1           16.0677      0.676     23.772      0.000      14.743      17.393
T2            -20.3024      1.646    -12.331      0.000     -23.530     -17.075
RH_2          -14.4106      0.774    -18.609      0.000     -15.929     -12.893
T3             25.3783      1.064     23.862      0.000      23.294      27.463
RH_3            5.0481      0.682      7.402      0.000       3.711       6.385
T4              2.9757      0.988      3.013      0.003       1.040       4.911
RH_4            1.9470      0.635      3.067      0.002       0.703       3.191
T5             -0.0111      1.186     -0.009      0.993      -2.336       2.314
RH_5            0.2391      0.088      2.727      0.006       0.067       0.411
T6              7.6617      0.640     11.965      0.000       6.407       8.917
RH_6            0.3472      0.068      5.073      0.000       0.213       0.481
T7              1.1305      1.337      0.845      0.398      -1.491       3.752
RH_7           -1.8431      0.434     -4.249      0.000      -2.694      -0.993
T8             10.1538      0.974     10.426      0.000       8.245      12.063
RH_8           -5.9065      0.372    -15.879      0.000      -6.636      -5.177
T9            -22.1081      1.755    -12.596      0.000     -25.548     -18.668
RH_9           -1.5000      0.413     -3.633      0.000      -2.309      -0.691
T_out         -10.6453      1.537     -6.924      0.000     -13.659      -7.632
Press_mm_hg     0.1230      0.108      1.138      0.255      -0.089       0.335
RH_out         -0.9120      0.318     -2.871      0.004      -1.535      -0.289
Windspeed       2.1293      0.348      6.111      0.000       1.446       2.812
Visibility      0.1762      0.058      3.019      0.003       0.062       0.291
Tdewpoint       5.0815      1.493      3.404      0.001       2.156       8.007
==============================================================================
Omnibus:                    14033.773   Durbin-Watson:                   0.608
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           213100.590
Skew:                           3.344   Prob(JB):                         0.00
Kurtosis:                      17.643   Cond. No.                     1.10e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [11]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
time_dataframe = dataframe
x = dataframe[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint']]
y = dataframe['lights']
linear_regression = LinearRegression()
linear_regression.fit(x, y)
print('Intercept: \n', linear_regression.intercept_)
print('Coefficients: \n', linear_regression.coef_)

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 
print_model = model.summary()
print(print_model)

Intercept:
 -7.439964893605826
Coefficients:
 [ 0.49947831  0.46044796 -1.30706445 -0.46898871 -0.01588944  0.06246379
  3.23981594  1.06951427  0.00385603  0.04883592  0.26805122  0.02982437
 -0.33481851 -0.14684802  1.00751733 -0.62061318 -3.12484426 -0.30350524
 -0.20710604 -0.00836014  0.07704723  0.2137526   0.01112127  0.01376361]
                            OLS Regression Results
==============================================================================
Dep. Variable:                 lights   R-squared:                       0.222
Model:                            OLS   Adj. R-squared:                  0.221
Method:                 Least Squares   F-statistic:                     233.9
Date:                Mon, 20 Mar 2023   Prob (F-statistic):               0.00
Time:                        15:56:44   Log-Likelihood:                -66408.
No. Observations:               19735   AIC:                         1.329e+05
Df Residuals:                   19710   BIC:                         1.331e+05
Df Model:                          24
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -7.4400      7.068     -1.053      0.293     -21.294       6.414
T1              0.4995      0.138      3.628      0.000       0.230       0.769
RH_1            0.4604      0.050      9.217      0.000       0.363       0.558
T2             -1.3071      0.122    -10.741      0.000      -1.546      -1.069
RH_2           -0.4690      0.057     -8.194      0.000      -0.581      -0.357
T3             -0.0159      0.079     -0.202      0.840      -0.170       0.138
RH_3            0.0625      0.050      1.239      0.215      -0.036       0.161
T4              3.2398      0.073     44.387      0.000       3.097       3.383
RH_4            1.0695      0.047     22.791      0.000       0.978       1.161
T5              0.0039      0.088      0.044      0.965      -0.168       0.176
RH_5            0.0488      0.006      7.536      0.000       0.036       0.062
T6              0.2681      0.047      5.663      0.000       0.175       0.361
RH_6            0.0298      0.005      5.897      0.000       0.020       0.040
T7             -0.3348      0.099     -3.387      0.001      -0.529      -0.141
RH_7           -0.1468      0.032     -4.580      0.000      -0.210      -0.084
T8              1.0075      0.072     13.996      0.000       0.866       1.149
RH_8           -0.6206      0.027    -22.573      0.000      -0.675      -0.567
T9             -3.1248      0.130    -24.088      0.000      -3.379      -2.871
RH_9           -0.3035      0.031     -9.944      0.000      -0.363      -0.244
T_out          -0.2071      0.114     -1.823      0.068      -0.430       0.016
Press_mm_hg    -0.0084      0.008     -1.046      0.296      -0.024       0.007
RH_out          0.0770      0.023      3.282      0.001       0.031       0.123
Windspeed       0.2138      0.026      8.300      0.000       0.163       0.264
Visibility      0.0111      0.004      2.578      0.010       0.003       0.020
Tdewpoint       0.0138      0.110      0.125      0.901      -0.202       0.230
==============================================================================
Omnibus:                     6665.474   Durbin-Watson:                   0.562
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            23267.281
Skew:                           1.705   Prob(JB):                         0.00
Kurtosis:                       7.082   Cond. No.                     1.10e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+05. This might indicate that there are
strong multicollinearity or other numerical problems.