In [1]:
import pandas
dataframe = pandas.read_csv("dataset.csv")
dataframe['date'] = pandas.to_datetime(dataframe['date'], format='%Y-%m-%d %H:%M:%S')

In [2]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  datetime64[ns]
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(2)
memory usage: 4.4 MB

In [3]:
dataframe.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
dataframe.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [5]:
print(list(dict.fromkeys(dataframe.columns)))

['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1', 'rv2']

In [6]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/feature_vs_date"
# DPI = 100
# for i in range(1 , 2):
# # for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         graph.title(column_list[i] + " vs " + column_list[0])
#         graph.xlabel(column_list[0])
#         graph.ylabel(column_list[i])
#         graph.plot(dataframe[column_list[0]], dataframe[column_list[i]], linewidth=1)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + ".png", dpi = DPI)
#         graph.show()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + ".png", dpi = DPI)
#         graph.show()

In [7]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/feature_vs_week1"
# filtered_week1_dataset = dataframe.loc[ ("2016-01-11" < dataframe["date"]) & (dataframe["date"] <= "2016-01-18")]
# DPI = 100
# # for i in range(1 , 2):
# for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         graph.title(column_list[i] + " vs " + column_list[0] + "(week 1)")
#         graph.xlabel(column_list[0])
#         graph.ylabel(column_list[i])
#         graph.plot(filtered_week1_dataset[column_list[0]], filtered_week1_dataset[column_list[i]], linewidth=1)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + "_week1.png", dpi = DPI)
#         graph.show()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)
#         graph.savefig(dir_structure + "/" + column_list[i] + "_vs_" + column_list[0] + "_week1.png", dpi = DPI)
#         graph.show()

In [8]:
# column_list = list(dict.fromkeys(dataframe.columns))
# dir_structure = "./graphs/frequency"
# DPI = 100
# for i in range(1 , 2):
# # for i in range(1 , len(column_list)):
#     try:
#         print(column_list[i] + "_vs_" + column_list[0])
#         import matplotlib.pyplot as graph
#         from matplotlib.pyplot import figure
#         figure(figsize=(32, 9), dpi=DPI)
#         feature_frequency_dataframe = dataframe[column_list[i]].value_counts()
#         feature_frequency_dataframe.hist()
#     except FileNotFoundError:
#         from pathlib import Path
#         Path(dir_structure).mkdir(parents=True, exist_ok=True)

In [9]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
time_dataframe = dataframe
x = dataframe[['lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint']]
y = dataframe['Appliances']
linear_regression = LinearRegression()
linear_regression.fit(x, y)
print('Intercept: \n', linear_regression.intercept_)
print('Coefficients: \n', linear_regression.coef_)

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 
print_model = model.summary()
print(print_model)

Intercept:
 49.46462587503224
Coefficients:
 [ 1.98965591e+00 -6.06385030e-01  1.51515388e+01 -1.77017707e+01
 -1.34775091e+01  2.54098652e+01  4.92377650e+00 -3.47045679e+00
 -1.80975329e-01 -1.87558665e-02  1.41906953e-01  7.12834412e+00
  2.87816027e-01  1.79671947e+00 -1.55097252e+00  8.14914928e+00
 -4.67168265e+00 -1.58907022e+01 -8.96177068e-01 -1.02332546e+01
  1.39665709e-01 -1.06532699e+00  1.70399317e+00  1.54069828e-01
  5.05406861e+00]
                            OLS Regression Results
==============================================================================
Dep. Variable:             Appliances   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.164
Method:                 Least Squares   F-statistic:                     155.6
Date:                Sun, 26 Mar 2023   Prob (F-statistic):               0.00
Time:                        03:18:10   Log-Likelihood:            -1.1760e+05
No. Observations:               19735   AIC:                         2.353e+05
Df Residuals:                   19709   BIC:                         2.355e+05
Df Model:                          25
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          49.4646     94.589      0.523      0.601    -135.938     234.868
lights          1.9897      0.095     20.873      0.000       1.803       2.176
T1             -0.6064      1.843     -0.329      0.742      -4.219       3.006
RH_1           15.1515      0.670     22.614      0.000      13.838      16.465
T2            -17.7018      1.633    -10.838      0.000     -20.903     -14.500
RH_2          -13.4775      0.767    -17.565      0.000     -14.981     -11.974
T3             25.4099      1.052     24.154      0.000      23.348      27.472
RH_3            4.9238      0.675      7.299      0.000       3.602       6.246
T4             -3.4705      1.024     -3.388      0.001      -5.478      -1.462
RH_4           -0.1810      0.636     -0.284      0.776      -1.428       1.066
T5             -0.0188      1.173     -0.016      0.987      -2.318       2.281
RH_5            0.1419      0.087      1.634      0.102      -0.028       0.312
T6              7.1283      0.634     11.245      0.000       5.886       8.371
RH_6            0.2878      0.068      4.249      0.000       0.155       0.421
T7              1.7967      1.323      1.358      0.175      -0.797       4.390
RH_7           -1.5510      0.429     -3.612      0.000      -2.393      -0.709
T8              8.1491      0.968      8.417      0.000       6.252      10.047
RH_8           -4.6717      0.373    -12.536      0.000      -5.402      -3.941
T9            -15.8907      1.761     -9.021      0.000     -19.343     -12.438
RH_9           -0.8962      0.409     -2.189      0.029      -1.699      -0.094
T_out         -10.2333      1.521     -6.728      0.000     -13.214      -7.252
Press_mm_hg     0.1397      0.107      1.306      0.192      -0.070       0.349
RH_out         -1.0653      0.314     -3.390      0.001      -1.681      -0.449
Windspeed       1.7040      0.345      4.935      0.000       1.027       2.381
Visibility      0.1541      0.058      2.668      0.008       0.041       0.267
Tdewpoint       5.0541      1.477      3.423      0.001       2.160       7.948
==============================================================================
Omnibus:                    13976.874   Durbin-Watson:                   0.625
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           211480.332
Skew:                           3.326   Prob(JB):                         0.00
Kurtosis:                      17.592   Cond. No.                     1.10e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
time_dataframe = dataframe
x = dataframe[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint']]
y = dataframe['lights']
linear_regression = LinearRegression()
linear_regression.fit(x, y)
print('Intercept: \n', linear_regression.intercept_)
print('Coefficients: \n', linear_regression.coef_)

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 
print_model = model.summary()
print(print_model)